spring.application.name=booknest
server.port=8080

datastax.astra.secure-connect-bundle=classpath:secure-connect-booknest.zip
spring.cassandra.keyspace-name=booknest
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
spring.cassandra.request.timeout=30s
spring.cassandra.connection.connect-timeout=30s
spring.cassandra.connection.init-query-timeout=30s

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.redirect-uri=https://booknest-production-a533.up.railway.app/login/oauth2/code/github

spring.cassandra.username=${ASTRA_CLIENT_ID}
spring.cassandra.password=${ASTRA_CLIENT_SECRET}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration

groq.api.key=${GROQ_API_KEY}

# FIX: Reduce memory usage to prevent Out of Memory crash on Railway free tier
server.tomcat.threads.max=10
server.tomcat.threads.min-spare=2
spring.codec.max-in-memory-size=10MB